#!/bin/bash

cursor --install-extension amazonwebservices.aws-toolkit-vscode
cursor --install-extension anysphere.cursorpyright
cursor --install-extension charliermarsh.ruff
cursor --install-extension christian-kohler.npm-intellisense
cursor --install-extension christian-kohler.path-intellisense
cursor --install-extension davidanson.vscode-markdownlint
cursor --install-extension dbaeumer.vscode-eslint
cursor --install-extension docker.docker
cursor --install-extension dustypomerleau.rust-syntax
cursor --install-extension eamodio.gitlens
cursor --install-extension esbenp.prettier-vscode
cursor --install-extension expo.vscode-expo-tools
cursor --install-extension fill-labs.dependi
cursor --install-extension fwcd.kotlin
cursor --install-extension github.copilot
cursor --install-extension github.copilot-chat
cursor --install-extension github.copilot-workspace
cursor --install-extension github.vscode-github-actions
cursor --install-extension github.vscode-pull-request-github
cursor --install-extension graphql.vscode-graphql
cursor --install-extension graphql.vscode-graphql-syntax
cursor --install-extension jaspernorth.vscode-pigments
cursor --install-extension johnpapa.vscode-peacock
cursor --install-extension juanblanco.solidity
cursor --install-extension mathiasfrohlich.kotlin
cursor --install-extension ms-azuretools.vscode-containers
cursor --install-extension ms-azuretools.vscode-docker
cursor --install-extension ms-dotnettools.csharp
cursor --install-extension ms-dotnettools.vscode-dotnet-runtime
cursor --install-extension ms-python.black-formatter
cursor --install-extension ms-python.debugpy
cursor --install-extension ms-python.isort
cursor --install-extension ms-python.python
cursor --install-extension ms-python.vscode-pylance
cursor --install-extension ms-python.vscode-python-envs
cursor --install-extension ms-toolsai.jupyter
cursor --install-extension ms-toolsai.jupyter-renderers
cursor --install-extension ms-toolsai.vscode-jupyter-cell-tags
cursor --install-extension ms-toolsai.vscode-jupyter-slideshow
cursor --install-extension oven.bun-vscode
cursor --install-extension pranaygp.vscode-css-peek
cursor --install-extension redhat.vscode-xml
cursor --install-extension redhat.vscode-yaml
cursor --install-extension shardulm94.trailing-spaces
cursor --install-extension svelte.svelte-vscode
cursor --install-extension tamasfe.even-better-toml
cursor --install-extension tobiah.unity-tools
cursor --install-extension vscode-icons-team.vscode-icons
cursor --install-extension wix.vscode-import-cost
cursor --install-extension zhuangtongfa.material-theme
