code --install-extension akamud.vscode-theme-onedark
code --install-extension christian-kohler.npm-intellisense
code --install-extension christian-kohler.path-intellisense
code --install-extension DavidAnson.vscode-markdownlint
code --install-extension dbaeumer.vscode-eslint
code --install-extension eamodio.gitlens
code --install-extension eg2.vscode-npm-script
code --install-extension esbenp.prettier-vscode
code --install-extension ferdelamad.styled-snippets
code --install-extension formulahendry.auto-close-tag
code --install-extension jaspernorth.vscode-pigments
code --install-extension johnpapa.vscode-peacock
code --install-extension matklad.rust-analyzer
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-dotnettools.csharp
code --install-extension ms-python.python
code --install-extension ms-vscode.csharp
code --install-extension pranaygp.vscode-css-peek
code --install-extension rust-lang.rust
code --install-extension shardulm94.trailing-spaces
code --install-extension Tobiah.unity-tools
code --install-extension Unity.unity-debug
code --install-extension vscode-icons-team.vscode-icons
code --install-extension wangchou.go-to-export
code --install-extension wix.vscode-import-cost
